services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: '/var/lib/postgresql/data/pgdata'

  nginx:
    build: ./config/nginx
    command: [ "nginx", "-g", "daemon off;" ]
    container_name: nginx
    restart: always
    links:
      - web
    volumes_from:
      - web
    ports:
      - "80:80"
      - "443:443"

  web:
    build: ./src
    container_name: web
    command: [ "./scripts/wait-for-it.sh", "$POSTGRES_SERVER:5432", "--", "./scripts/start.sh"]
    restart: always
    volumes:
      - ./config:/opt/conf
#      - ./src:/content_master
#      - ./src/static:/content_master/static
      - static-data:/content_master/static
    expose:
      - "3000"
    environment:
      DJANGO_SETTINGS_MODULE: "contentMaster.settings.prod"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  app-db-data:
  static-data:
