# Generated by Django 5.1.1 on 2024-09-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityauthor',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_author', to='blog_generator.author'),
        ),
        migrations.CreateModel(
            name='ProfileAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_author', to='blog_generator.author')),
            ],
        ),
    ]
