# Generated by Django 5.1.1 on 2024-09-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0003_blog_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
