# Generated by Django 5.1.1 on 2024-09-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0006_rename_theme_author_niche_rename_theme_blog_niche_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='keywords',
            new_name='phrases',
        ),
    ]
